name: componly

on:
  workflow_dispatch:
   inputs:
      commitName:
        description: 'Custom commit name'
        required: true
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 18

      - name: Install dependencies
        id: install-dependencies
        run: yarn install && yarn add @componlyco/cli -D
      
      - name: Scan
        id: componly-scan
        env:
          MIN_COVERAGE: 60
          COMPONLY_CLI_KEY: ZETTP0
        run: npx componly coverage --design-systems=@componlyco/berkoukes,@mui/material
